spring.application.name=dashboard-engine
server.port=8080

#logging.level.org.springframework=DEBUG


pipedrive.api.url=https://santorisantafe.pipedrive.com/v1
pipedrive.api.token=8e45bbae49b6078ada0c5a49b150751d253c1e8a

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

